/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

module cordic_trig_16bit_simple_fixed(clk, rst_n, start, angle, cosine, sine, done, ready);
  wire [31:0] _000_;
  wire [15:0] _001_;
  wire [31:0] _002_;
  wire [15:0] _003_;
  wire [31:0] _004_;
  wire [15:0] _005_;
  wire [31:0] _006_;
  wire [15:0] _007_;
  wire [31:0] _008_;
  wire [15:0] _009_;
  wire [31:0] _010_;
  wire [15:0] _011_;
  wire [31:0] _012_;
  wire [15:0] _013_;
  wire [31:0] _014_;
  wire [15:0] _015_;
  wire [31:0] _016_;
  wire [15:0] _017_;
  wire [31:0] _018_;
  wire [15:0] _019_;
  wire [31:0] _020_;
  wire [15:0] _021_;
  wire [31:0] _022_;
  wire [15:0] _023_;
  wire [31:0] _024_;
  wire [15:0] _025_;
  wire [31:0] _026_;
  wire [15:0] _027_;
  wire [31:0] _028_;
  wire [15:0] _029_;
  wire [31:0] _030_;
  wire [15:0] _031_;
  wire [15:0] _032_;
  wire [31:0] _033_;
  wire [31:0] _034_;
  wire _035_;
  wire [3:0] _036_;
  wire [1:0] _037_;
  wire _038_;
  wire [15:0] _039_;
  wire [31:0] _040_;
  wire [31:0] _041_;
  wire [1:0] _042_;
  wire [16:0] _043_;
  wire [31:0] _044_;
  wire [16:0] _045_;
  wire [31:0] _046_;
  wire [15:0] _047_;
  wire [31:0] _048_;
  wire [1:0] _049_;
  wire [15:0] _050_;
  wire [31:0] _051_;
  wire [31:0] _052_;
  wire [31:0] _053_;
  wire [31:0] _054_;
  wire [1:0] _055_;
  wire [15:0] _056_;
  wire [31:0] _057_;
  wire [31:0] _058_;
  wire [31:0] _059_;
  wire [31:0] _060_;
  wire [1:0] _061_;
  wire [15:0] _062_;
  wire [31:0] _063_;
  wire [31:0] _064_;
  wire [15:0] _065_;
  wire [31:0] _066_;
  wire [31:0] _067_;
  wire [15:0] _068_;
  wire [31:0] _069_;
  wire [15:0] _070_;
  wire [16:0] _071_;
  wire [15:0] _072_;
  wire [16:0] _073_;
  wire [31:0] _074_;
  wire [31:0] _075_;
  wire [31:0] _076_;
  wire [31:0] _077_;
  wire [31:0] _078_;
  wire [31:0] _079_;
  wire [31:0] _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [15:0] _090_;
  wire [15:0] _091_;
  wire [31:0] _092_;
  wire [15:0] _093_;
  wire [31:0] _094_;
  wire [15:0] _095_;
  wire [31:0] _096_;
  wire [15:0] _097_;
  wire [31:0] _098_;
  wire [15:0] _099_;
  wire [31:0] _100_;
  wire [15:0] _101_;
  wire [31:0] _102_;
  wire [15:0] _103_;
  wire [31:0] _104_;
  wire [15:0] _105_;
  wire [31:0] _106_;
  wire [15:0] _107_;
  wire [31:0] _108_;
  wire [15:0] _109_;
  wire [31:0] _110_;
  wire [15:0] _111_;
  wire [31:0] _112_;
  wire [15:0] _113_;
  wire [31:0] _114_;
  wire [15:0] _115_;
  wire [31:0] _116_;
  wire [15:0] _117_;
  wire [31:0] _118_;
  wire [15:0] _119_;
  wire [31:0] _120_;
  wire [15:0] _121_;
  wire [31:0] _122_;
  wire [15:0] _123_;
  wire [31:0] _124_;
  wire [31:0] _125_;
  wire [31:0] _126_;
  wire [31:0] _127_;
  wire [31:0] _128_;
  wire _129_;
  wire [31:0] _130_;
  wire _131_;
  wire [31:0] _132_;
  wire _133_;
  wire [31:0] _134_;
  wire _135_;
  wire [31:0] _136_;
  wire _137_;
  wire [31:0] _138_;
  wire _139_;
  wire [31:0] _140_;
  wire _141_;
  wire [31:0] _142_;
  wire _143_;
  wire [31:0] _144_;
  wire _145_;
  wire [31:0] _146_;
  wire _147_;
  wire [31:0] _148_;
  wire _149_;
  wire [31:0] _150_;
  wire _151_;
  wire [31:0] _152_;
  wire _153_;
  wire [31:0] _154_;
  wire _155_;
  wire [31:0] _156_;
  wire _157_;
  wire [31:0] _158_;
  wire _159_;
  wire [31:0] _160_;
  wire _161_;
  wire [31:0] _162_;
  wire _163_;
  wire [15:0] _164_;
  wire _165_;
  wire [15:0] _166_;
  wire _167_;
  wire [15:0] _168_;
  wire _169_;
  wire [15:0] _170_;
  wire _171_;
  wire [15:0] _172_;
  wire _173_;
  wire [15:0] _174_;
  wire _175_;
  wire [15:0] _176_;
  wire _177_;
  wire [15:0] _178_;
  wire _179_;
  wire [15:0] _180_;
  wire _181_;
  wire [15:0] _182_;
  wire _183_;
  wire [15:0] _184_;
  wire _185_;
  wire [15:0] _186_;
  wire _187_;
  wire [15:0] _188_;
  wire _189_;
  wire [15:0] _190_;
  wire _191_;
  wire [15:0] _192_;
  wire _193_;
  wire [31:0] _194_;
  wire _195_;
  wire [31:0] _196_;
  wire _197_;
  wire [31:0] _198_;
  wire _199_;
  wire [31:0] _200_;
  wire _201_;
  wire [15:0] _202_;
  wire _203_;
  wire [15:0] _204_;
  wire _205_;
  wire [15:0] _206_;
  wire _207_;
  wire [15:0] _208_;
  wire _209_;
  wire [15:0] _210_;
  wire _211_;
  wire _212_;
  wire [16:0] _213_;
  wire _214_;
  wire [16:0] _215_;
  wire _216_;
  wire [16:0] _217_;
  wire _218_;
  wire [16:0] _219_;
  wire _220_;
  wire [16:0] _221_;
  wire _222_;
  wire [16:0] _223_;
  wire _224_;
  wire _225_;
  wire [16:0] _226_;
  wire _227_;
  wire [16:0] _228_;
  wire _229_;
  wire [16:0] _230_;
  wire _231_;
  wire [16:0] _232_;
  wire _233_;
  wire [16:0] _234_;
  wire _235_;
  wire [16:0] _236_;
  wire _237_;
  wire _238_;
  wire [3:0] _239_;
  wire _240_;
  wire [3:0] _241_;
  wire _242_;
  wire _243_;
  wire [31:0] _244_;
  wire _245_;
  wire [31:0] _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire [1:0] _255_;
  wire _256_;
  wire [1:0] _257_;
  wire _258_;
  wire [1:0] _259_;
  wire _260_;
  wire [1:0] _261_;
  wire _262_;
  wire [1:0] _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire [31:0] _267_;
  wire [31:0] _268_;
  wire [31:0] _269_;
  wire [31:0] _270_;
  wire [31:0] _271_;
  wire [31:0] _272_;
  wire [16:0] _273_;
  wire [16:0] _274_;
  wire [16:0] _275_;
  wire [16:0] _276_;
  wire [15:0] _277_;
  wire [15:0] _278_;
  wire [15:0] _279_;
  wire [16:0] _280_;
  wire [16:0] _281_;
  wire [15:0] _282_;
  input [15:0] angle;
  reg [15:0] angle_reg;
  input clk;
  reg [31:0] cos_result;
  output [31:0] cosine;
  reg [31:0] cosine;
  output done;
  reg done;
  wire [31:0] i;
  reg [3:0] iteration;
  wire [1:0] next_state;
  output ready;
  reg ready;
  reg [15:0] reduced_angle;
  input rst_n;
  reg [31:0] sin_result;
  output [31:0] sine;
  reg [31:0] sine;
  input start;
  reg [1:0] state;
  reg [16:0] x;
  reg [31:0] x_scaled;
  reg [16:0] y;
  reg [31:0] y_scaled;
  reg [15:0] z;
  reg [15:0] atan_table [15:0];
  assign _071_ = x + _273_;
  assign _072_ = z + _090_;
  assign _073_ = y + _276_;
  assign _074_ = iteration + 32'd1;
  assign _075_ = { x[15:0], 16'h0000 } + _267_;
  assign _076_ = _075_ + _268_;
  assign _077_ = _076_ + _269_;
  assign _078_ = { y[15:0], 16'h0000 } + _270_;
  assign _079_ = _078_ + _271_;
  assign _080_ = _079_ + _272_;
  assign _081_ = iteration == 32'd15;
  assign _082_ = ! rst_n;
  assign _083_ = ! rst_n;
  assign _084_ = angle < 32'd16384;
  assign _085_ = angle < 32'd32768;
  assign _086_ = angle < 32'd49152;
  assign _087_ = angle_reg < 32'd16384;
  assign _088_ = angle_reg < 32'd32768;
  assign _089_ = angle_reg < 32'd49152;
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd185),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _302_ (
    .ADDR(_092_),
    .DATA(_093_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd186),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _303_ (
    .ADDR(_094_),
    .DATA(_095_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd187),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _304_ (
    .ADDR(_096_),
    .DATA(_097_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd188),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _305_ (
    .ADDR(_098_),
    .DATA(_099_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd189),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _306_ (
    .ADDR(_100_),
    .DATA(_101_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd190),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _307_ (
    .ADDR(_102_),
    .DATA(_103_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd191),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _308_ (
    .ADDR(_104_),
    .DATA(_105_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd192),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _309_ (
    .ADDR(_106_),
    .DATA(_107_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd193),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _310_ (
    .ADDR(_108_),
    .DATA(_109_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd194),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _311_ (
    .ADDR(_110_),
    .DATA(_111_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd195),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _312_ (
    .ADDR(_112_),
    .DATA(_113_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd196),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _313_ (
    .ADDR(_114_),
    .DATA(_115_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd197),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _314_ (
    .ADDR(_116_),
    .DATA(_117_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd198),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _315_ (
    .ADDR(_118_),
    .DATA(_119_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd199),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _316_ (
    .ADDR(_120_),
    .DATA(_121_)
  );
  \$meminit  #(
    .ABITS(32'd32),
    .MEMID("\\atan_table"),
    .PRIORITY(32'd200),
    .WIDTH(32'd16),
    .WORDS(32'd1)
  ) _317_ (
    .ADDR(_122_),
    .DATA(_123_)
  );
  \$memrd  #(
    .ABITS(32'd4),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\atan_table"),
    .TRANSPARENT(32'd0),
    .WIDTH(32'd16)
  ) _318_ (
    .ADDR(iteration),
    .CLK(1'hx),
    .DATA(_090_),
    .EN(1'hx)
  );
  \$memrd  #(
    .ABITS(32'd4),
    .CLK_ENABLE(32'd0),
    .CLK_POLARITY(32'd0),
    .MEMID("\\atan_table"),
    .TRANSPARENT(32'd0),
    .WIDTH(32'd16)
  ) _319_ (
    .ADDR(iteration),
    .CLK(1'hx),
    .DATA(_091_),
    .EN(1'hx)
  );
  assign _124_ = - _080_;
  assign _125_ = - _077_;
  assign _126_ = - _080_;
  assign _127_ = - _077_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      done <= 1'h0;
    else
      done <= _252_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      ready <= 1'h1;
    else
      ready <= _250_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      cosine <= 32'd0;
    else
      cosine <= _246_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      sine <= 32'd0;
    else
      sine <= _244_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      x_scaled <= 32'd0;
    else
      x_scaled <= _200_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      iteration <= 4'h0;
    else
      iteration <= _239_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      x <= 17'h00000;
    else
      x <= _228_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      y <= 17'h00000;
    else
      y <= _215_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      z <= 16'h0000;
    else
      z <= _208_;
  always @(posedge clk)
      angle_reg <= _204_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      reduced_angle <= 16'h0000;
    else
      reduced_angle <= _192_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      y_scaled <= 32'd0;
    else
      y_scaled <= _198_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      cos_result <= 32'd0;
    else
      cos_result <= _196_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      sin_result <= 32'd0;
    else
      sin_result <= _194_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      state <= 2'h0;
    else
      state <= _263_;
  assign _128_ = _129_ ? _126_ : _127_;
  assign _130_ = _131_ ? 32'hxxxxxxxx : _128_;
  assign _132_ = _133_ ? 32'hxxxxxxxx : _130_;
  assign _134_ = _135_ ? _132_ : 32'hxxxxxxxx;
  assign _135_ = state == 2'h2;
  assign _136_ = _137_ ? _125_ : _080_;
  assign _138_ = _139_ ? 32'hxxxxxxxx : _136_;
  assign _140_ = _141_ ? 32'hxxxxxxxx : _138_;
  assign _142_ = _143_ ? _140_ : 32'hxxxxxxxx;
  assign _143_ = state == 2'h2;
  assign _144_ = _145_ ? _077_ : _069_;
  assign _146_ = _147_ ? 32'hxxxxxxxx : _144_;
  assign _148_ = _149_ ? _146_ : 32'hxxxxxxxx;
  assign _149_ = state == 2'h2;
  assign _150_ = _151_ ? _124_ : _067_;
  assign _152_ = _153_ ? 32'hxxxxxxxx : _150_;
  assign _154_ = _155_ ? _152_ : 32'hxxxxxxxx;
  assign _155_ = state == 2'h2;
  assign _156_ = _157_ ? _080_ : _066_;
  assign _158_ = _159_ ? _156_ : 32'hxxxxxxxx;
  assign _159_ = state == 2'h2;
  assign _160_ = _161_ ? _077_ : _064_;
  assign _162_ = _163_ ? _160_ : 32'hxxxxxxxx;
  assign _163_ = state == 2'h2;
  assign _164_ = _165_ ? _278_ : _279_;
  assign _166_ = _167_ ? 16'hxxxx : _164_;
  assign _168_ = _169_ ? 16'hxxxx : _166_;
  assign _170_ = _171_ ? _168_ : 16'hxxxx;
  assign _172_ = _173_ ? _170_ : 16'hxxxx;
  assign _173_ = state == 2'h0;
  assign _174_ = _175_ ? _277_ : _070_;
  assign _176_ = _177_ ? 16'hxxxx : _174_;
  assign _178_ = _179_ ? _176_ : 16'hxxxx;
  assign _180_ = _181_ ? _178_ : 16'hxxxx;
  assign _181_ = state == 2'h0;
  assign _182_ = _183_ ? angle : _068_;
  assign _184_ = _185_ ? _182_ : 16'hxxxx;
  assign _186_ = _187_ ? _184_ : 16'hxxxx;
  assign _187_ = state == 2'h0;
  assign _188_ = _189_ ? _065_ : reduced_angle;
  assign _190_ = _191_ ? _188_ : 16'hxxxx;
  assign _191_ = state == 2'h0;
  assign _192_ = _193_ ? _062_ : reduced_angle;
  assign _193_ = state == 2'h0;
  assign _194_ = _195_ ? _063_ : sin_result;
  assign _195_ = state == 2'h2;
  assign _196_ = _197_ ? _060_ : cos_result;
  assign _197_ = state == 2'h2;
  assign _198_ = _199_ ? _080_ : y_scaled;
  assign _199_ = state == 2'h2;
  assign _200_ = _201_ ? _077_ : x_scaled;
  assign _201_ = state == 2'h2;
  assign _202_ = _203_ ? angle : angle_reg;
  assign _204_ = _205_ ? _202_ : angle_reg;
  assign _205_ = state == 2'h0;
  assign _206_ = _207_ ? _072_ : _282_;
  function [15:0] _395_;
    input [15:0] a;
    input [31:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _395_ = b[15:0];
      2'b1?:
        _395_ = b[31:16];
      default:
        _395_ = a;
    endcase
  endfunction
  assign _208_ = _395_(z, { _210_, _206_ }, { _212_, _209_ });
  assign _209_ = state == 2'h1;
  assign _210_ = _211_ ? _065_ : z;
  assign _212_ = state == 2'h0;
  assign _213_ = _214_ ? _280_ : _073_;
  function [16:0] _400_;
    input [16:0] a;
    input [33:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _400_ = b[16:0];
      2'b1?:
        _400_ = b[33:17];
      default:
        _400_ = a;
    endcase
  endfunction
  assign _215_ = _400_(y, { _223_, _213_ }, { _225_, _216_ });
  assign _216_ = state == 2'h1;
  assign _217_ = _218_ ? 17'h00000 : 17'h1648b;
  assign _219_ = _220_ ? 17'h09b75 : _217_;
  assign _221_ = _222_ ? 17'h00000 : _219_;
  assign _223_ = _224_ ? _221_ : y;
  assign _225_ = state == 2'h0;
  assign _226_ = _227_ ? _071_ : _281_;
  function [16:0] _408_;
    input [16:0] a;
    input [33:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _408_ = b[16:0];
      2'b1?:
        _408_ = b[33:17];
      default:
        _408_ = a;
    endcase
  endfunction
  assign _228_ = _408_(x, { _236_, _226_ }, { _238_, _229_ });
  assign _229_ = state == 2'h1;
  assign _230_ = _231_ ? 17'h1648b : 17'h00000;
  assign _232_ = _233_ ? 17'h00000 : _230_;
  assign _234_ = _235_ ? 17'h09b75 : _232_;
  assign _236_ = _237_ ? _234_ : x;
  assign _238_ = state == 2'h0;
  function [3:0] _415_;
    input [3:0] a;
    input [7:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _415_ = b[3:0];
      2'b1?:
        _415_ = b[7:4];
      default:
        _415_ = a;
    endcase
  endfunction
  assign _239_ = _415_(iteration, { _241_, _074_[3:0] }, { _243_, _240_ });
  assign _240_ = state == 2'h1;
  assign _241_ = _242_ ? 4'h0 : iteration;
  assign _243_ = state == 2'h0;
  assign _244_ = _245_ ? _063_ : sine;
  assign _245_ = state == 2'h2;
  assign _246_ = _247_ ? _060_ : cosine;
  assign _247_ = state == 2'h2;
  assign _248_ = _249_ ? 1'h0 : 1'h1;
  assign _250_ = _251_ ? _248_ : ready;
  assign _251_ = state == 2'h0;
  function [0:0] _426_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _426_ = b[0:0];
      2'b1?:
        _426_ = b[1:1];
      default:
        _426_ = a;
    endcase
  endfunction
  assign _252_ = _426_(done, 2'h1, { _254_, _253_ });
  assign _253_ = state == 2'h2;
  assign _254_ = state == 2'h0;
  assign _255_ = _256_ ? 2'h2 : state;
  assign _257_ = _258_ ? _255_ : 2'hx;
  assign _258_ = state == 2'h1;
  assign _259_ = _260_ ? 2'h1 : state;
  assign _261_ = _262_ ? _259_ : 2'hx;
  assign _262_ = state == 2'h0;
  function [1:0] _435_;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _435_ = b[1:0];
      3'b?1?:
        _435_ = b[3:2];
      3'b1??:
        _435_ = b[5:4];
      default:
        _435_ = a;
    endcase
  endfunction
  assign _263_ = _435_(state, { _055_, _061_, 2'h0 }, { _266_, _265_, _264_ });
  assign _264_ = state == 2'h2;
  assign _265_ = state == 2'h1;
  assign _266_ = state == 2'h0;
  assign _267_ = { x[15:0], 16'h0000 } >> $signed(32'd1);
  assign _268_ = { x[15:0], 16'h0000 } >> $signed(32'd3);
  assign _269_ = { x[15:0], 16'h0000 } >> $signed(32'd6);
  assign _270_ = { y[15:0], 16'h0000 } >> $signed(32'd1);
  assign _271_ = { y[15:0], 16'h0000 } >> $signed(32'd3);
  assign _272_ = { y[15:0], 16'h0000 } >> $signed(32'd6);
  assign _273_ = y >>> iteration;
  assign _274_ = x >>> iteration;
  assign _275_ = y >>> iteration;
  assign _276_ = x >>> iteration;
  assign _277_ = angle - 16'h4000;
  assign _278_ = angle - 16'h8000;
  assign _279_ = angle - 16'hc000;
  assign _280_ = y - _274_;
  assign _281_ = x - _275_;
  assign _282_ = z - _091_;
  assign _031_ = 16'h0000;
  assign _030_ = 32'd15;
  assign _029_ = 16'h0001;
  assign _028_ = 32'd14;
  assign _027_ = 16'h0001;
  assign _026_ = 32'd13;
  assign _025_ = 16'h0003;
  assign _024_ = 32'd12;
  assign _023_ = 16'h0005;
  assign _022_ = 32'd11;
  assign _021_ = 16'h000a;
  assign _020_ = 32'd10;
  assign _019_ = 16'h0014;
  assign _018_ = 32'd9;
  assign _017_ = 16'h0029;
  assign _016_ = 32'd8;
  assign _015_ = 16'h0051;
  assign _014_ = 32'd7;
  assign _013_ = 16'h00a3;
  assign _012_ = 32'd6;
  assign _011_ = 16'h0146;
  assign _010_ = 32'd5;
  assign _009_ = 16'h028b;
  assign _008_ = 32'd4;
  assign _007_ = 16'h0511;
  assign _006_ = 32'd3;
  assign _005_ = 16'h09fb;
  assign _004_ = 32'd2;
  assign _003_ = 16'h12e4;
  assign _002_ = 32'd1;
  assign _001_ = 16'h2000;
  assign _000_ = 32'd0;
  assign _129_ = _089_;
  assign _131_ = _088_;
  assign _133_ = _087_;
  assign _069_ = _134_;
  assign _137_ = _089_;
  assign _139_ = _088_;
  assign _141_ = _087_;
  assign _067_ = _142_;
  assign _145_ = _088_;
  assign _147_ = _087_;
  assign _066_ = _148_;
  assign _151_ = _088_;
  assign _153_ = _087_;
  assign _064_ = _154_;
  assign _157_ = _087_;
  assign _063_ = _158_;
  assign _161_ = _087_;
  assign _060_ = _162_;
  assign _165_ = _086_;
  assign _167_ = _085_;
  assign _169_ = _084_;
  assign _171_ = start;
  assign _070_ = _172_;
  assign _175_ = _085_;
  assign _177_ = _084_;
  assign _179_ = start;
  assign _068_ = _180_;
  assign _183_ = _084_;
  assign _185_ = start;
  assign _065_ = _186_;
  assign _189_ = start;
  assign _062_ = _190_;
  assign _056_ = _192_;
  assign _057_ = _194_;
  assign _054_ = _196_;
  assign _059_ = _198_;
  assign _058_ = _200_;
  assign _051_ = _057_;
  assign _048_ = _054_;
  assign _053_ = _059_;
  assign _050_ = _056_;
  assign _052_ = _058_;
  assign _040_ = _051_;
  assign _033_ = _048_;
  assign _046_ = _053_;
  assign _039_ = _050_;
  assign _044_ = _052_;
  assign _203_ = start;
  assign _032_ = _204_;
  assign _207_ = z[15];
  assign _211_ = start;
  assign _047_ = _208_;
  assign _214_ = z[15];
  assign _218_ = _086_;
  assign _220_ = _085_;
  assign _222_ = _084_;
  assign _224_ = start;
  assign _045_ = _215_;
  assign _227_ = z[15];
  assign _231_ = _086_;
  assign _233_ = _085_;
  assign _235_ = _084_;
  assign _237_ = start;
  assign _043_ = _228_;
  assign _242_ = start;
  assign _036_ = _239_;
  assign _041_ = _244_;
  assign _034_ = _246_;
  assign _249_ = start;
  assign _038_ = _250_;
  assign _035_ = _252_;
  assign _256_ = _081_;
  assign _061_ = _257_;
  assign _260_ = start;
  assign _055_ = _261_;
  assign _049_ = _263_;
  assign _037_ = _049_;
  assign _042_ = next_state;
  assign _092_ = 32'd0;
  assign _093_ = 16'h2000;
  assign _094_ = 32'd1;
  assign _095_ = 16'h12e4;
  assign _096_ = 32'd2;
  assign _097_ = 16'h09fb;
  assign _098_ = 32'd3;
  assign _099_ = 16'h0511;
  assign _100_ = 32'd4;
  assign _101_ = 16'h028b;
  assign _102_ = 32'd5;
  assign _103_ = 16'h0146;
  assign _104_ = 32'd6;
  assign _105_ = 16'h00a3;
  assign _106_ = 32'd7;
  assign _107_ = 16'h0051;
  assign _108_ = 32'd8;
  assign _109_ = 16'h0029;
  assign _110_ = 32'd9;
  assign _111_ = 16'h0014;
  assign _112_ = 32'd10;
  assign _113_ = 16'h000a;
  assign _114_ = 32'd11;
  assign _115_ = 16'h0005;
  assign _116_ = 32'd12;
  assign _117_ = 16'h0003;
  assign _118_ = 32'd13;
  assign _119_ = 16'h0001;
  assign _120_ = 32'd14;
  assign _121_ = 16'h0001;
  assign _122_ = 32'd15;
  assign _123_ = 16'h0000;
  assign next_state = _263_;
endmodule

module div_mod_3(n, quotient, remainder);
  wire [6:0] _00_;
  wire [5:0] _01_;
  wire [4:0] _02_;
  wire [1:0] _03_;
  wire [7:0] _04_;
  wire [7:0] _05_;
  wire [7:0] _06_;
  wire [31:0] _07_;
  wire _08_;
  wire _09_;
  wire [31:0] _10_;
  wire [31:0] _11_;
  wire [1:0] _12_;
  input [7:0] n;
  wire [5:0] q1;
  wire [4:0] q2;
  wire [3:0] q3;
  wire [1:0] q4;
  output [7:0] quotient;
  wire [7:0] quotient_sum;
  wire [1:0] r1;
  wire [1:0] r2;
  wire [1:0] r3;
  wire [1:0] r4;
  wire [6:0] rem1;
  wire [5:0] rem2;
  wire [4:0] rem3;
  wire [1:0] rem4;
  output [1:0] remainder;
  assign _00_ = q1 + r1;
  assign _01_ = q2 + r2;
  assign _02_ = q3 + r3;
  assign _03_ = q4 + r4;
  assign _04_ = q1 + q2;
  assign _05_ = _04_ + q3;
  assign _06_ = _05_ + q4;
  assign _07_ = quotient_sum + 32'd1;
  assign _08_ = rem4 == 2'h3;
  assign _09_ = rem4 == 2'h3;
  assign _10_ = + quotient_sum;
  assign _11_ = _08_ ? _07_ : _10_;
  assign _12_ = _09_ ? 2'h0 : rem4;
  assign q1 = n[7:2];
  assign r1 = n[1:0];
  assign rem1 = _00_;
  assign q2 = rem1[6:2];
  assign r2 = rem1[1:0];
  assign rem2 = _01_;
  assign q3 = rem2[5:2];
  assign r3 = rem2[1:0];
  assign rem3 = _02_;
  assign q4 = rem3[3:2];
  assign r4 = rem3[1:0];
  assign rem4 = _03_;
  assign quotient_sum = _06_;
  assign quotient = _11_[7:0];
  assign remainder = _12_;
endmodule

module div_mod_7(n, quotient, remainder);
  wire [6:0] _00_;
  wire [4:0] _01_;
  wire [2:0] _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  wire [31:0] _05_;
  wire _06_;
  wire _07_;
  wire [31:0] _08_;
  wire [31:0] _09_;
  wire [2:0] _10_;
  input [8:0] n;
  wire [5:0] q1;
  wire [3:0] q2;
  wire [1:0] q3;
  output [8:0] quotient;
  wire [7:0] quotient_sum;
  wire [2:0] r1;
  wire [2:0] r2;
  wire [2:0] r3;
  wire [6:0] rem1;
  wire [4:0] rem2;
  wire [2:0] rem3;
  output [2:0] remainder;
  assign _00_ = q1 + r1;
  assign _01_ = q2 + r2;
  assign _02_ = q3 + r3;
  assign _03_ = q1 + q2;
  assign _04_ = _03_ + q3;
  assign _05_ = quotient_sum + 32'd1;
  assign _06_ = rem3 == 3'h7;
  assign _07_ = rem3 == 3'h7;
  assign _08_ = + quotient_sum;
  assign _09_ = _06_ ? _05_ : _08_;
  assign _10_ = _07_ ? 3'h0 : rem3;
  assign q1 = n[8:3];
  assign r1 = n[2:0];
  assign rem1 = _00_;
  assign q2 = rem1[6:3];
  assign r2 = rem1[2:0];
  assign rem2 = _01_;
  assign q3 = rem2[4:3];
  assign r3 = rem2[2:0];
  assign rem3 = _02_;
  assign quotient_sum = _04_;
  assign quotient = _09_[8:0];
  assign remainder = _10_;
endmodule

module sphere3hopf_fsm_32bit_simple(clk, rst_n, start, k_in, base_sel0, base_sel1, base_sel2, result_x, result_y, result_z, result_w, done, ready);
  wire [31:0] _000_;
  wire [31:0] _001_;
  wire [63:0] _002_;
  wire [63:0] _003_;
  wire [31:0] _004_;
  wire [31:0] _005_;
  wire [31:0] _006_;
  wire [31:0] _007_;
  wire [31:0] _008_;
  wire [63:0] _009_;
  wire [63:0] _010_;
  wire [31:0] _011_;
  wire [31:0] _012_;
  wire [31:0] _013_;
  wire [31:0] _014_;
  wire [31:0] _015_;
  wire [31:0] _016_;
  wire [4:0] _017_;
  wire _018_;
  wire [31:0] _019_;
  wire [4:0] _020_;
  wire [31:0] _021_;
  wire [31:0] _022_;
  wire [31:0] _023_;
  wire _024_;
  wire [31:0] _025_;
  wire [31:0] _026_;
  wire [31:0] _027_;
  wire [31:0] _028_;
  wire [31:0] _029_;
  wire [31:0] _030_;
  wire [31:0] _031_;
  wire [31:0] _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire [31:0] _037_;
  wire [63:0] _038_;
  wire [31:0] _039_;
  wire [31:0] _040_;
  wire [63:0] _041_;
  wire [63:0] _042_;
  wire [31:0] _043_;
  wire [31:0] _044_;
  wire [31:0] _045_;
  wire [31:0] _046_;
  wire [31:0] _047_;
  wire [63:0] _048_;
  wire [63:0] _049_;
  wire [31:0] _050_;
  wire [31:0] _051_;
  wire [31:0] _052_;
  wire [4:0] _053_;
  wire [31:0] _054_;
  wire [63:0] _055_;
  wire [31:0] _056_;
  wire [31:0] _057_;
  wire [63:0] _058_;
  wire [63:0] _059_;
  wire [31:0] _060_;
  wire [31:0] _061_;
  wire [31:0] _062_;
  wire [31:0] _063_;
  wire [31:0] _064_;
  wire [63:0] _065_;
  wire [63:0] _066_;
  wire [31:0] _067_;
  wire [31:0] _068_;
  wire [31:0] _069_;
  wire [4:0] _070_;
  wire [31:0] _071_;
  wire [63:0] _072_;
  wire [31:0] _073_;
  wire [31:0] _074_;
  wire [63:0] _075_;
  wire [63:0] _076_;
  wire [31:0] _077_;
  wire [31:0] _078_;
  wire [31:0] _079_;
  wire [31:0] _080_;
  wire [31:0] _081_;
  wire [63:0] _082_;
  wire [63:0] _083_;
  wire [31:0] _084_;
  wire [31:0] _085_;
  wire [31:0] _086_;
  wire [4:0] _087_;
  wire [31:0] _088_;
  wire [63:0] _089_;
  wire [63:0] _090_;
  wire [63:0] _091_;
  wire [31:0] _092_;
  wire [31:0] _093_;
  wire [63:0] _094_;
  wire [63:0] _095_;
  wire [31:0] _096_;
  wire [31:0] _097_;
  wire [4:0] _098_;
  wire [4:0] _099_;
  wire [4:0] _100_;
  wire [31:0] _101_;
  wire [31:0] _102_;
  wire [31:0] _103_;
  wire [31:0] _104_;
  wire [31:0] _105_;
  wire [31:0] _106_;
  wire [31:0] _107_;
  wire [63:0] _108_;
  wire [63:0] _109_;
  wire [63:0] _110_;
  wire [63:0] _111_;
  reg [31:0] _112_;
  reg [31:0] _113_;
  reg [63:0] _114_;
  reg [63:0] _115_;
  reg [31:0] _116_;
  reg [31:0] _117_;
  reg [31:0] _118_;
  reg [31:0] _119_;
  reg [31:0] _120_;
  reg [63:0] _121_;
  reg [63:0] _122_;
  reg [31:0] _123_;
  reg [31:0] _124_;
  reg [31:0] _125_;
  wire _126_;
  wire _127_;
  wire [31:0] _128_;
  wire [31:0] _129_;
  wire [63:0] _130_;
  wire [31:0] _131_;
  wire [31:0] _132_;
  wire [31:0] _133_;
  wire [31:0] _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire [31:0] _139_;
  wire _140_;
  wire [31:0] _141_;
  wire _142_;
  wire [31:0] _143_;
  wire _144_;
  wire [31:0] _145_;
  wire _146_;
  wire [31:0] _147_;
  wire _148_;
  wire [31:0] _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire [31:0] _158_;
  wire _159_;
  wire [31:0] _160_;
  wire _161_;
  wire [31:0] _162_;
  wire _163_;
  wire [31:0] _164_;
  wire _165_;
  wire [4:0] _166_;
  wire _167_;
  wire [4:0] _168_;
  wire _169_;
  wire [4:0] _170_;
  wire _171_;
  wire [4:0] _172_;
  wire _173_;
  wire [4:0] _174_;
  wire _175_;
  wire [4:0] _176_;
  wire _177_;
  wire [4:0] _178_;
  wire _179_;
  wire [4:0] _180_;
  wire _181_;
  wire [4:0] _182_;
  wire _183_;
  wire [4:0] _184_;
  wire _185_;
  wire [4:0] _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire [31:0] _198_;
  wire _199_;
  wire [31:0] _200_;
  wire _201_;
  wire [31:0] _202_;
  wire _203_;
  wire [63:0] _204_;
  wire _205_;
  wire [63:0] _206_;
  wire _207_;
  wire [63:0] _208_;
  wire _209_;
  wire [31:0] _210_;
  wire _211_;
  wire [31:0] _212_;
  wire _213_;
  wire [31:0] _214_;
  wire _215_;
  wire [63:0] _216_;
  wire _217_;
  wire [63:0] _218_;
  wire _219_;
  wire [63:0] _220_;
  wire _221_;
  wire [31:0] _222_;
  wire _223_;
  wire [31:0] _224_;
  wire _225_;
  wire [31:0] _226_;
  wire _227_;
  wire [63:0] _228_;
  wire _229_;
  wire [63:0] _230_;
  wire _231_;
  wire [63:0] _232_;
  wire _233_;
  wire [31:0] _234_;
  wire _235_;
  wire [31:0] _236_;
  wire _237_;
  wire [31:0] _238_;
  wire _239_;
  wire [63:0] _240_;
  wire _241_;
  wire [63:0] _242_;
  wire _243_;
  wire [63:0] _244_;
  wire _245_;
  wire [31:0] _246_;
  wire _247_;
  wire [31:0] _248_;
  wire _249_;
  wire [63:0] _250_;
  wire _251_;
  wire [63:0] _252_;
  wire _253_;
  wire [31:0] _254_;
  wire _255_;
  wire [31:0] _256_;
  wire _257_;
  wire [63:0] _258_;
  wire _259_;
  wire [63:0] _260_;
  wire _261_;
  wire [31:0] _262_;
  wire _263_;
  wire [31:0] _264_;
  wire _265_;
  wire [31:0] _266_;
  wire _267_;
  wire [31:0] _268_;
  wire _269_;
  wire [31:0] _270_;
  wire _271_;
  wire [31:0] _272_;
  wire _273_;
  wire [31:0] _274_;
  wire _275_;
  wire [31:0] _276_;
  wire _277_;
  wire [63:0] _278_;
  wire _279_;
  wire [63:0] _280_;
  wire _281_;
  wire [31:0] _282_;
  wire _283_;
  wire [31:0] _284_;
  wire _285_;
  wire [63:0] _286_;
  wire _287_;
  wire [63:0] _288_;
  wire _289_;
  wire [31:0] _290_;
  wire _291_;
  wire [31:0] _292_;
  wire _293_;
  wire [31:0] _294_;
  wire _295_;
  wire [31:0] _296_;
  wire _297_;
  wire [31:0] _298_;
  wire _299_;
  wire [31:0] _300_;
  wire _301_;
  wire [31:0] _302_;
  wire _303_;
  wire [31:0] _304_;
  wire _305_;
  wire [63:0] _306_;
  wire _307_;
  wire [63:0] _308_;
  wire _309_;
  wire [63:0] _310_;
  wire _311_;
  wire [63:0] _312_;
  wire _313_;
  wire [31:0] _314_;
  wire _315_;
  wire [31:0] _316_;
  wire _317_;
  wire [31:0] _318_;
  wire _319_;
  wire [31:0] _320_;
  wire _321_;
  wire [31:0] _322_;
  wire _323_;
  wire [63:0] _324_;
  wire _325_;
  wire [63:0] _326_;
  wire _327_;
  wire [31:0] _328_;
  wire _329_;
  wire [31:0] _330_;
  wire _331_;
  wire [31:0] _332_;
  wire _333_;
  wire [31:0] _334_;
  wire _335_;
  wire [31:0] _336_;
  wire _337_;
  wire [31:0] _338_;
  wire _339_;
  wire [63:0] _340_;
  wire _341_;
  wire [31:0] _342_;
  wire _343_;
  wire [31:0] _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire [31:0] _362_;
  wire _363_;
  wire [31:0] _364_;
  wire _365_;
  wire [31:0] _366_;
  wire _367_;
  wire [31:0] _368_;
  wire _369_;
  wire [31:0] _370_;
  wire _371_;
  wire [31:0] _372_;
  wire _373_;
  wire [31:0] _374_;
  wire _375_;
  wire [31:0] _376_;
  wire _377_;
  wire [31:0] _378_;
  wire _379_;
  wire [31:0] _380_;
  wire _381_;
  wire [31:0] _382_;
  wire _383_;
  wire [31:0] _384_;
  wire _385_;
  wire [31:0] _386_;
  wire _387_;
  wire [31:0] _388_;
  wire _389_;
  wire [63:0] _390_;
  wire [63:0] _391_;
  wire [63:0] _392_;
  wire [63:0] _393_;
  wire [31:0] _394_;
  wire [31:0] _395_;
  wire [31:0] _396_;
  wire [31:0] _397_;
  wire [31:0] _398_;
  wire [31:0] _399_;
  wire [63:0] _400_;
  wire [31:0] _401_;
  wire [31:0] _402_;
  wire [31:0] _403_;
  wire [31:0] _404_;
  wire [63:0] _405_;
  input [1:0] base_sel0;
  input [1:0] base_sel1;
  input [1:0] base_sel2;
  input clk;
  reg [31:0] cos_eta_reg;
  reg [31:0] cos_phi_psi_reg;
  reg [31:0] cos_psi_reg;
  reg [4:0] current_state;
  output done;
  reg done;
  input [31:0] k_in;
  reg [31:0] k_reg;
  wire [4:0] next_state;
  reg [31:0] one_minus_vdc;
  reg [31:0] phi_reg;
  reg [31:0] psi_reg;
  output ready;
  reg ready;
  output [31:0] result_w;
  reg [31:0] result_w;
  output [31:0] result_x;
  reg [31:0] result_x;
  output [31:0] result_y;
  reg [31:0] result_y;
  output [31:0] result_z;
  reg [31:0] result_z;
  input rst_n;
  reg [31:0] sin_eta_reg;
  reg [31:0] sin_phi_psi_reg;
  reg [31:0] sin_psi_reg;
  input start;
  reg [31:0] trig_angle;
  wire [31:0] trig_cos;
  wire trig_done;
  wire [31:0] trig_sin;
  reg trig_start;
  wire vdc0_done;
  wire vdc0_ready;
  wire [31:0] vdc0_result;
  reg vdc0_start;
  wire vdc1_done;
  wire vdc1_ready;
  wire [31:0] vdc1_result;
  reg vdc1_start;
  wire vdc2_done;
  wire vdc2_ready;
  wire [31:0] vdc2_result;
  reg vdc2_start;
  reg [31:0] vdc_reg;
  reg [63:0] vdc_sq;
  assign _101_ = vdc_reg + 32'd32768;
  assign _102_ = _405_[31:0] + 32'd32768;
  assign _103_ = _101_ + _108_[31:0];
  assign _104_ = _102_ + _109_[31:0];
  assign _105_ = _096_ + _111_[31:0];
  assign _106_ = _092_ + _110_[31:0];
  assign _107_ = phi_reg + psi_reg;
  assign _108_ = _390_ / _101_;
  assign _109_ = _391_ / _102_;
  assign _110_ = _392_ / _092_;
  assign _111_ = _393_ / _096_;
  assign _126_ = ! rst_n;
  assign _127_ = ! rst_n;
  assign _128_ = vdc0_result * 32'd411774;
  assign _129_ = vdc1_result * 32'd411774;
  assign _130_ = vdc_reg * vdc_reg;
  assign _131_ = cos_eta_reg * cos_psi_reg;
  assign _132_ = cos_eta_reg * sin_psi_reg;
  assign _133_ = sin_eta_reg * cos_phi_psi_reg;
  assign _134_ = sin_eta_reg * sin_phi_psi_reg;
  assign _135_ = _101_ != 32'd0;
  assign _136_ = _102_ != 32'd0;
  assign _137_ = _092_ != 32'd0;
  assign _138_ = _096_ != 32'd0;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      result_x <= 32'd0;
    else
      result_x <= _164_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      result_y <= 32'd0;
    else
      result_y <= _162_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      result_z <= 32'd0;
    else
      result_z <= _160_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      result_w <= 32'd0;
    else
      result_w <= _158_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      done <= 1'h0;
    else
      done <= _155_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      ready <= 1'h1;
    else
      ready <= _153_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      k_reg <= 32'd0;
    else
      k_reg <= _149_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      phi_reg <= 32'd0;
    else
      phi_reg <= _145_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      psi_reg <= 32'd0;
    else
      psi_reg <= _141_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      vdc_reg <= 32'd0;
    else
      vdc_reg <= _388_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      cos_eta_reg <= 32'd0;
    else
      cos_eta_reg <= _384_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      sin_eta_reg <= 32'd0;
    else
      sin_eta_reg <= _380_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      cos_psi_reg <= 32'd0;
    else
      cos_psi_reg <= _376_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      sin_psi_reg <= 32'd0;
    else
      sin_psi_reg <= _372_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      cos_phi_psi_reg <= 32'd0;
    else
      cos_phi_psi_reg <= _368_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      sin_phi_psi_reg <= 32'd0;
    else
      sin_phi_psi_reg <= _364_;
  always @(posedge clk)
      vdc_sq <= _340_;
  always @(posedge clk)
      one_minus_vdc <= _338_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      vdc0_start <= 1'h0;
    else
      vdc0_start <= _359_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      vdc1_start <= 1'h0;
    else
      vdc1_start <= _356_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      vdc2_start <= 1'h0;
    else
      vdc2_start <= _353_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      trig_start <= 1'h0;
    else
      trig_start <= _347_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      trig_angle <= 32'd0;
    else
      trig_angle <= _344_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _112_ <= 32'hxxxxxxxx;
    else
      _112_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _113_ <= 32'hxxxxxxxx;
    else
      _113_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _116_ <= 32'hxxxxxxxx;
    else
      _116_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _117_ <= 32'hxxxxxxxx;
    else
      _117_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _118_ <= 32'hxxxxxxxx;
    else
      _118_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _114_ <= 64'hxxxxxxxxxxxxxxxx;
    else
      _114_ <= 64'hxxxxxxxxxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _115_ <= 64'hxxxxxxxxxxxxxxxx;
    else
      _115_ <= 64'hxxxxxxxxxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _119_ <= 32'hxxxxxxxx;
    else
      _119_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _120_ <= 32'hxxxxxxxx;
    else
      _120_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _123_ <= 32'hxxxxxxxx;
    else
      _123_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _124_ <= 32'hxxxxxxxx;
    else
      _124_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _125_ <= 32'hxxxxxxxx;
    else
      _125_ <= 32'hxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _121_ <= 64'hxxxxxxxxxxxxxxxx;
    else
      _121_ <= 64'hxxxxxxxxxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      _122_ <= 64'hxxxxxxxxxxxxxxxx;
    else
      _122_ <= 64'hxxxxxxxxxxxxxxxx;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      current_state <= 5'h00;
    else
      current_state <= _186_;
  assign _139_ = _140_ ? _399_ : psi_reg;
  assign _141_ = _142_ ? _139_ : psi_reg;
  assign _142_ = current_state == 5'h04;
  assign _143_ = _144_ ? _398_ : phi_reg;
  assign _145_ = _146_ ? _143_ : phi_reg;
  assign _146_ = current_state == 5'h02;
  assign _147_ = _148_ ? k_in : k_reg;
  assign _149_ = _150_ ? _147_ : k_reg;
  assign _150_ = current_state == 5'h00;
  assign _151_ = _152_ ? 1'h0 : 1'h1;
  assign _153_ = _154_ ? _151_ : ready;
  assign _154_ = current_state == 5'h00;
  function [0:0] _480_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _480_ = b[0:0];
      2'b1?:
        _480_ = b[1:1];
      default:
        _480_ = a;
    endcase
  endfunction
  assign _155_ = _480_(done, 2'h1, { _157_, _156_ });
  assign _156_ = current_state == 5'h0b;
  assign _157_ = current_state == 5'h00;
  assign _158_ = _159_ ? _404_ : result_w;
  assign _159_ = current_state == 5'h0a;
  assign _160_ = _161_ ? _403_ : result_z;
  assign _161_ = current_state == 5'h0a;
  assign _162_ = _163_ ? _402_ : result_y;
  assign _163_ = current_state == 5'h0a;
  assign _164_ = _165_ ? _401_ : result_x;
  assign _165_ = current_state == 5'h0a;
  assign _166_ = _167_ ? 5'h09 : current_state;
  assign _168_ = _169_ ? _166_ : 5'hxx;
  assign _169_ = current_state == 5'h08;
  assign _170_ = _171_ ? 5'h07 : current_state;
  assign _172_ = _173_ ? _170_ : 5'hxx;
  assign _173_ = current_state == 5'h06;
  assign _174_ = _175_ ? 5'h05 : current_state;
  assign _176_ = _177_ ? _174_ : 5'hxx;
  assign _177_ = current_state == 5'h04;
  assign _178_ = _179_ ? 5'h03 : current_state;
  assign _180_ = _181_ ? _178_ : 5'hxx;
  assign _181_ = current_state == 5'h02;
  assign _182_ = _183_ ? 5'h01 : current_state;
  assign _184_ = _185_ ? _182_ : 5'hxx;
  assign _185_ = current_state == 5'h00;
  function [4:0] _506_;
    input [4:0] a;
    input [54:0] b;
    input [10:0] s;
    casez (s) // synopsys parallel_case
      11'b??????????1:
        _506_ = b[4:0];
      11'b?????????1?:
        _506_ = b[9:5];
      11'b????????1??:
        _506_ = b[14:10];
      11'b???????1???:
        _506_ = b[19:15];
      11'b??????1????:
        _506_ = b[24:20];
      11'b?????1?????:
        _506_ = b[29:25];
      11'b????1??????:
        _506_ = b[34:30];
      11'b???1???????:
        _506_ = b[39:35];
      11'b??1????????:
        _506_ = b[44:40];
      11'b?1?????????:
        _506_ = b[49:45];
      11'b1??????????:
        _506_ = b[54:50];
      default:
        _506_ = a;
    endcase
  endfunction
  assign _186_ = _506_(5'h00, { _070_, 5'h02, _087_, 5'h04, _098_, 5'h06, _099_, 5'h08, _100_, 10'h14b }, { _197_, _196_, _195_, _194_, _193_, _192_, _191_, _190_, _189_, _188_, _187_ });
  assign _187_ = current_state == 5'h0a;
  assign _188_ = current_state == 5'h09;
  assign _189_ = current_state == 5'h08;
  assign _190_ = current_state == 5'h07;
  assign _191_ = current_state == 5'h06;
  assign _192_ = current_state == 5'h05;
  assign _193_ = current_state == 5'h04;
  assign _194_ = current_state == 5'h03;
  assign _195_ = current_state == 5'h02;
  assign _196_ = current_state == 5'h01;
  assign _197_ = current_state == 5'h00;
  assign _198_ = _199_ ? _396_ : 32'd0;
  assign _200_ = _201_ ? _198_ : 32'hxxxxxxxx;
  assign _202_ = _203_ ? _200_ : 32'hxxxxxxxx;
  assign _203_ = current_state == 5'h09;
  assign _204_ = _205_ ? _111_ : _122_;
  assign _206_ = _207_ ? _204_ : 64'hxxxxxxxxxxxxxxxx;
  assign _208_ = _209_ ? _206_ : 64'hxxxxxxxxxxxxxxxx;
  assign _209_ = current_state == 5'h09;
  assign _210_ = _211_ ? _395_ : 32'd0;
  assign _212_ = _213_ ? _210_ : 32'hxxxxxxxx;
  assign _214_ = _215_ ? _212_ : 32'hxxxxxxxx;
  assign _215_ = current_state == 5'h09;
  assign _216_ = _217_ ? _109_ : _121_;
  assign _218_ = _219_ ? _216_ : 64'hxxxxxxxxxxxxxxxx;
  assign _220_ = _221_ ? _218_ : 64'hxxxxxxxxxxxxxxxx;
  assign _221_ = current_state == 5'h09;
  assign _222_ = _223_ ? _397_ : 32'd0;
  assign _224_ = _225_ ? _222_ : 32'hxxxxxxxx;
  assign _226_ = _227_ ? _224_ : 32'hxxxxxxxx;
  assign _227_ = current_state == 5'h09;
  assign _228_ = _229_ ? _110_ : _115_;
  assign _230_ = _231_ ? _228_ : 64'hxxxxxxxxxxxxxxxx;
  assign _232_ = _233_ ? _230_ : 64'hxxxxxxxxxxxxxxxx;
  assign _233_ = current_state == 5'h09;
  assign _234_ = _235_ ? _394_ : 32'd0;
  assign _236_ = _237_ ? _234_ : 32'hxxxxxxxx;
  assign _238_ = _239_ ? _236_ : 32'hxxxxxxxx;
  assign _239_ = current_state == 5'h09;
  assign _240_ = _241_ ? _108_ : _114_;
  assign _242_ = _243_ ? _240_ : 64'hxxxxxxxxxxxxxxxx;
  assign _244_ = _245_ ? _242_ : 64'hxxxxxxxxxxxxxxxx;
  assign _245_ = current_state == 5'h09;
  assign _246_ = _247_ ? _097_ : _119_;
  assign _248_ = _249_ ? _246_ : 32'hxxxxxxxx;
  assign _249_ = current_state == 5'h09;
  assign _250_ = _251_ ? _095_ : _122_;
  assign _252_ = _253_ ? _250_ : 64'hxxxxxxxxxxxxxxxx;
  assign _253_ = current_state == 5'h09;
  assign _254_ = _255_ ? _097_ : _125_;
  assign _256_ = _257_ ? _254_ : 32'hxxxxxxxx;
  assign _257_ = current_state == 5'h09;
  assign _258_ = _259_ ? _094_ : _121_;
  assign _260_ = _261_ ? _258_ : 64'hxxxxxxxxxxxxxxxx;
  assign _261_ = current_state == 5'h09;
  assign _262_ = _263_ ? _096_ : _124_;
  assign _264_ = _265_ ? _262_ : 32'hxxxxxxxx;
  assign _265_ = current_state == 5'h09;
  assign _266_ = _267_ ? _102_ : _123_;
  assign _268_ = _269_ ? _266_ : 32'hxxxxxxxx;
  assign _269_ = current_state == 5'h09;
  assign _270_ = _271_ ? _405_[31:0] : _120_;
  assign _272_ = _273_ ? _270_ : 32'hxxxxxxxx;
  assign _273_ = current_state == 5'h09;
  assign _274_ = _275_ ? _093_ : _112_;
  assign _276_ = _277_ ? _274_ : 32'hxxxxxxxx;
  assign _277_ = current_state == 5'h09;
  assign _278_ = _279_ ? _091_ : _115_;
  assign _280_ = _281_ ? _278_ : 64'hxxxxxxxxxxxxxxxx;
  assign _281_ = current_state == 5'h09;
  assign _282_ = _283_ ? _093_ : _118_;
  assign _284_ = _285_ ? _282_ : 32'hxxxxxxxx;
  assign _285_ = current_state == 5'h09;
  assign _286_ = _287_ ? _090_ : _114_;
  assign _288_ = _289_ ? _286_ : 64'hxxxxxxxxxxxxxxxx;
  assign _289_ = current_state == 5'h09;
  assign _290_ = _291_ ? _092_ : _117_;
  assign _292_ = _293_ ? _290_ : 32'hxxxxxxxx;
  assign _293_ = current_state == 5'h09;
  assign _294_ = _295_ ? _101_ : _116_;
  assign _296_ = _297_ ? _294_ : 32'hxxxxxxxx;
  assign _297_ = current_state == 5'h09;
  assign _298_ = _299_ ? vdc_reg : _113_;
  assign _300_ = _301_ ? _298_ : 32'hxxxxxxxx;
  assign _301_ = current_state == 5'h09;
  assign _302_ = _303_ ? _405_[31:0] : one_minus_vdc;
  assign _304_ = _305_ ? _302_ : 32'hxxxxxxxx;
  assign _305_ = current_state == 5'h09;
  assign _306_ = _307_ ? _130_ : vdc_sq;
  assign _308_ = _309_ ? _306_ : 64'hxxxxxxxxxxxxxxxx;
  assign _309_ = current_state == 5'h09;
  assign _310_ = _311_ ? _083_ : _122_;
  assign _311_ = current_state == 5'h09;
  assign _312_ = _313_ ? _082_ : _121_;
  assign _313_ = current_state == 5'h09;
  assign _314_ = _315_ ? _086_ : _125_;
  assign _315_ = current_state == 5'h09;
  assign _316_ = _317_ ? _085_ : _124_;
  assign _317_ = current_state == 5'h09;
  assign _318_ = _319_ ? _084_ : _123_;
  assign _319_ = current_state == 5'h09;
  assign _320_ = _321_ ? _081_ : _120_;
  assign _321_ = current_state == 5'h09;
  assign _322_ = _323_ ? _080_ : _119_;
  assign _323_ = current_state == 5'h09;
  assign _324_ = _325_ ? _076_ : _115_;
  assign _325_ = current_state == 5'h09;
  assign _326_ = _327_ ? _075_ : _114_;
  assign _327_ = current_state == 5'h09;
  assign _328_ = _329_ ? _079_ : _118_;
  assign _329_ = current_state == 5'h09;
  assign _330_ = _331_ ? _078_ : _117_;
  assign _331_ = current_state == 5'h09;
  assign _332_ = _333_ ? _077_ : _116_;
  assign _333_ = current_state == 5'h09;
  assign _334_ = _335_ ? _074_ : _113_;
  assign _335_ = current_state == 5'h09;
  assign _336_ = _337_ ? _073_ : _112_;
  assign _337_ = current_state == 5'h09;
  assign _338_ = _339_ ? _088_ : one_minus_vdc;
  assign _339_ = current_state == 5'h09;
  assign _340_ = _341_ ? _089_ : vdc_sq;
  assign _341_ = current_state == 5'h09;
  assign _342_ = _343_ ? _107_ : trig_angle;
  function [31:0] _631_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _631_ = b[31:0];
      2'b1?:
        _631_ = b[63:32];
      default:
        _631_ = a;
    endcase
  endfunction
  assign _344_ = _631_(trig_angle, { psi_reg, _342_ }, { _346_, _345_ });
  assign _345_ = current_state == 5'h08;
  assign _346_ = current_state == 5'h07;
  function [0:0] _634_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _634_ = b[0:0];
      3'b?1?:
        _634_ = b[1:1];
      3'b1??:
        _634_ = b[2:2];
      default:
        _634_ = a;
    endcase
  endfunction
  assign _347_ = _634_(trig_start, { 1'h1, _349_, 1'h0 }, { _352_, _351_, _348_ });
  assign _348_ = current_state == 5'h09;
  assign _349_ = _350_ ? 1'h1 : 1'h0;
  assign _351_ = current_state == 5'h08;
  assign _352_ = current_state == 5'h07;
  function [0:0] _639_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _639_ = b[0:0];
      2'b1?:
        _639_ = b[1:1];
      default:
        _639_ = a;
    endcase
  endfunction
  assign _353_ = _639_(vdc2_start, 2'h2, { _355_, _354_ });
  assign _354_ = current_state == 5'h06;
  assign _355_ = current_state == 5'h05;
  function [0:0] _642_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _642_ = b[0:0];
      2'b1?:
        _642_ = b[1:1];
      default:
        _642_ = a;
    endcase
  endfunction
  assign _356_ = _642_(vdc1_start, 2'h2, { _358_, _357_ });
  assign _357_ = current_state == 5'h04;
  assign _358_ = current_state == 5'h03;
  function [0:0] _645_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _645_ = b[0:0];
      2'b1?:
        _645_ = b[1:1];
      default:
        _645_ = a;
    endcase
  endfunction
  assign _359_ = _645_(vdc0_start, 2'h2, { _361_, _360_ });
  assign _360_ = current_state == 5'h02;
  assign _361_ = current_state == 5'h01;
  assign _362_ = _363_ ? trig_sin : sin_phi_psi_reg;
  assign _364_ = _365_ ? _362_ : sin_phi_psi_reg;
  assign _365_ = current_state == 5'h09;
  assign _366_ = _367_ ? trig_cos : cos_phi_psi_reg;
  assign _368_ = _369_ ? _366_ : cos_phi_psi_reg;
  assign _369_ = current_state == 5'h09;
  assign _370_ = _371_ ? trig_sin : sin_psi_reg;
  assign _372_ = _373_ ? _370_ : sin_psi_reg;
  assign _373_ = current_state == 5'h08;
  assign _374_ = _375_ ? trig_cos : cos_psi_reg;
  assign _376_ = _377_ ? _374_ : cos_psi_reg;
  assign _377_ = current_state == 5'h08;
  assign _378_ = _379_ ? _097_ : sin_eta_reg;
  assign _380_ = _381_ ? _378_ : sin_eta_reg;
  assign _381_ = current_state == 5'h09;
  assign _382_ = _383_ ? _093_ : cos_eta_reg;
  assign _384_ = _385_ ? _382_ : cos_eta_reg;
  assign _385_ = current_state == 5'h09;
  assign _386_ = _387_ ? vdc2_result : vdc_reg;
  assign _388_ = _389_ ? _386_ : vdc_reg;
  assign _389_ = current_state == 5'h06;
  assign _390_ = vdc_reg << $signed(32'd16);
  assign _391_ = _405_[31:0] << $signed(32'd16);
  assign _392_ = vdc_reg << $signed(32'd16);
  assign _393_ = _405_[31:0] << $signed(32'd16);
  assign _394_ = _103_ >> $signed(32'd1);
  assign _395_ = _104_ >> $signed(32'd1);
  assign _396_ = _105_ >> $signed(32'd1);
  assign _397_ = _106_ >> $signed(32'd1);
  assign _398_ = _128_ >> $signed(32'd16);
  assign _399_ = _129_ >> $signed(32'd16);
  assign _400_ = _130_ >> $signed(32'd16);
  assign _401_ = _131_ >> $signed(32'd16);
  assign _402_ = _132_ >> $signed(32'd16);
  assign _403_ = _133_ >> $signed(32'd16);
  assign _404_ = _134_ >> $signed(32'd16);
  assign _405_ = 32'd65536 - _400_;
  cordic_trig_16bit_simple_fixed trig_inst (
    .angle(trig_angle[31:16]),
    .clk(clk),
    .cosine(trig_cos),
    .done(trig_done),
    .ready(),
    .rst_n(rst_n),
    .sine(trig_sin),
    .start(trig_start)
  );
  vdcorput_fsm_32bit_simple vdc0_inst (
    .base_sel(base_sel0),
    .clk(clk),
    .done(vdc0_done),
    .k_in(k_reg),
    .ready(vdc0_ready),
    .result(vdc0_result),
    .rst_n(rst_n),
    .start(vdc0_start)
  );
  vdcorput_fsm_32bit_simple vdc1_inst (
    .base_sel(base_sel1),
    .clk(clk),
    .done(vdc1_done),
    .k_in(k_reg),
    .ready(vdc1_ready),
    .result(vdc1_result),
    .rst_n(rst_n),
    .start(vdc1_start)
  );
  vdcorput_fsm_32bit_simple vdc2_inst (
    .base_sel(base_sel2),
    .clk(clk),
    .done(vdc2_done),
    .k_in(k_reg),
    .ready(vdc2_ready),
    .result(vdc2_result),
    .rst_n(rst_n),
    .start(vdc2_start)
  );
  assign _199_ = _138_;
  assign _201_ = trig_done;
  assign _097_ = _202_;
  assign _205_ = _138_;
  assign _207_ = trig_done;
  assign _095_ = _208_;
  assign _211_ = _136_;
  assign _213_ = trig_done;
  assign _096_ = _214_;
  assign _217_ = _136_;
  assign _219_ = trig_done;
  assign _094_ = _220_;
  assign _223_ = _137_;
  assign _225_ = trig_done;
  assign _093_ = _226_;
  assign _229_ = _137_;
  assign _231_ = trig_done;
  assign _091_ = _232_;
  assign _235_ = _135_;
  assign _237_ = trig_done;
  assign _092_ = _238_;
  assign _241_ = _135_;
  assign _243_ = trig_done;
  assign _090_ = _244_;
  assign _247_ = trig_done;
  assign _080_ = _248_;
  assign _251_ = trig_done;
  assign _083_ = _252_;
  assign _255_ = trig_done;
  assign _086_ = _256_;
  assign _259_ = trig_done;
  assign _082_ = _260_;
  assign _263_ = trig_done;
  assign _085_ = _264_;
  assign _267_ = trig_done;
  assign _084_ = _268_;
  assign _271_ = trig_done;
  assign _081_ = _272_;
  assign _275_ = trig_done;
  assign _073_ = _276_;
  assign _279_ = trig_done;
  assign _076_ = _280_;
  assign _283_ = trig_done;
  assign _079_ = _284_;
  assign _287_ = trig_done;
  assign _075_ = _288_;
  assign _291_ = trig_done;
  assign _078_ = _292_;
  assign _295_ = trig_done;
  assign _077_ = _296_;
  assign _299_ = trig_done;
  assign _074_ = _300_;
  assign _303_ = trig_done;
  assign _088_ = _304_;
  assign _307_ = trig_done;
  assign _089_ = _308_;
  assign _066_ = _310_;
  assign _065_ = _312_;
  assign _069_ = _314_;
  assign _068_ = _316_;
  assign _067_ = _318_;
  assign _064_ = _320_;
  assign _063_ = _322_;
  assign _059_ = _324_;
  assign _058_ = _326_;
  assign _062_ = _328_;
  assign _061_ = _330_;
  assign _060_ = _332_;
  assign _057_ = _334_;
  assign _056_ = _336_;
  assign _071_ = _338_;
  assign _072_ = _340_;
  assign _049_ = _066_;
  assign _048_ = _065_;
  assign _052_ = _069_;
  assign _051_ = _068_;
  assign _050_ = _067_;
  assign _047_ = _064_;
  assign _046_ = _063_;
  assign _042_ = _059_;
  assign _041_ = _058_;
  assign _045_ = _062_;
  assign _044_ = _061_;
  assign _043_ = _060_;
  assign _040_ = _057_;
  assign _039_ = _056_;
  assign _054_ = _071_;
  assign _055_ = _072_;
  assign _010_ = _049_;
  assign _009_ = _048_;
  assign _013_ = _052_;
  assign _012_ = _051_;
  assign _011_ = _050_;
  assign _008_ = _047_;
  assign _007_ = _046_;
  assign _003_ = _042_;
  assign _002_ = _041_;
  assign _006_ = _045_;
  assign _005_ = _044_;
  assign _004_ = _043_;
  assign _001_ = _040_;
  assign _000_ = _039_;
  assign _021_ = _054_;
  assign _038_ = _055_;
  assign _343_ = trig_done;
  assign _032_ = _344_;
  assign _350_ = trig_done;
  assign _033_ = _347_;
  assign _036_ = _353_;
  assign _035_ = _356_;
  assign _034_ = _359_;
  assign _363_ = trig_done;
  assign _030_ = _364_;
  assign _367_ = trig_done;
  assign _015_ = _368_;
  assign _371_ = trig_done;
  assign _031_ = _372_;
  assign _375_ = trig_done;
  assign _016_ = _376_;
  assign _379_ = trig_done;
  assign _029_ = _380_;
  assign _383_ = trig_done;
  assign _014_ = _384_;
  assign _387_ = vdc2_done;
  assign _037_ = _388_;
  assign _140_ = vdc1_done;
  assign _023_ = _141_;
  assign _144_ = vdc0_done;
  assign _022_ = _145_;
  assign _148_ = start;
  assign _019_ = _149_;
  assign _152_ = start;
  assign _024_ = _153_;
  assign _018_ = _155_;
  assign _025_ = _158_;
  assign _028_ = _160_;
  assign _027_ = _162_;
  assign _026_ = _164_;
  assign _167_ = trig_done;
  assign _100_ = _168_;
  assign _171_ = vdc2_done;
  assign _099_ = _172_;
  assign _175_ = vdc1_done;
  assign _098_ = _176_;
  assign _179_ = vdc0_done;
  assign _087_ = _180_;
  assign _183_ = start;
  assign _070_ = _184_;
  assign _053_ = _186_;
  assign _020_ = _053_;
  assign _017_ = next_state;
  assign next_state = _186_;
endmodule

module vdcorput_fsm_32bit_simple(clk, rst_n, start, k_in, base_sel, result, done, ready);
  wire [31:0] _000_;
  wire [31:0] _001_;
  wire [2:0] _002_;
  wire _003_;
  wire [31:0] _004_;
  wire [2:0] _005_;
  wire [31:0] _006_;
  wire [31:0] _007_;
  wire _008_;
  wire [31:0] _009_;
  wire [31:0] _010_;
  wire [2:0] _011_;
  wire [2:0] _012_;
  wire [2:0] _013_;
  wire [31:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire [31:0] _018_;
  wire [31:0] _019_;
  wire [31:0] _020_;
  wire _021_;
  wire [31:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire [31:0] _026_;
  wire _027_;
  wire [31:0] _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [31:0] _032_;
  wire _033_;
  wire [31:0] _034_;
  wire _035_;
  wire _036_;
  wire [31:0] _037_;
  wire _038_;
  wire [31:0] _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire [31:0] _043_;
  wire _044_;
  wire [31:0] _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire [31:0] _049_;
  wire _050_;
  wire [31:0] _051_;
  wire _052_;
  wire _053_;
  wire [31:0] _054_;
  wire _055_;
  wire [31:0] _056_;
  wire _057_;
  wire [31:0] _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire [2:0] _068_;
  wire _069_;
  wire [2:0] _070_;
  wire _071_;
  wire [2:0] _072_;
  wire _073_;
  wire [2:0] _074_;
  wire _075_;
  wire [2:0] _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire [31:0] _083_;
  wire [31:0] _084_;
  wire [31:0] _085_;
  wire [31:0] _086_;
  reg [31:0] acc_reg;
  reg [31:0] base_reg;
  input [1:0] base_sel;
  input clk;
  reg [2:0] current_state;
  wire [7:0] div3_quotient;
  wire [1:0] div3_remainder;
  wire [8:0] div7_quotient;
  wire [2:0] div7_remainder;
  output done;
  reg done;
  input [31:0] k_in;
  reg [31:0] k_reg;
  wire [2:0] next_state;
  reg [31:0] power_reg;
  reg [31:0] quotient_reg;
  output ready;
  reg ready;
  reg [31:0] remainder_reg;
  output [31:0] result;
  reg [31:0] result;
  input rst_n;
  input start;
  assign _014_ = acc_reg + _018_;
  assign _015_ = k_reg == 32'd0;
  assign _016_ = ! rst_n;
  assign _017_ = ! rst_n;
  assign _018_ = remainder_reg * power_reg;
  assign _019_ = power_reg * 32'd21845;
  assign _020_ = power_reg * 32'd9362;
  assign _021_ = remainder_reg != 32'd0;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      done <= 1'h0;
    else
      done <= _065_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      ready <= 1'h1;
    else
      ready <= _063_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      k_reg <= 32'd0;
    else
      k_reg <= _056_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      result <= 32'd0;
    else
      result <= _054_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      acc_reg <= 32'd0;
    else
      acc_reg <= _051_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      power_reg <= 32'd65536;
    else
      power_reg <= _043_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      base_reg <= 32'd2;
    else
      base_reg <= _037_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      remainder_reg <= 32'd0;
    else
      remainder_reg <= _032_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      quotient_reg <= 32'd0;
    else
      quotient_reg <= _026_;
  always @(posedge clk or negedge rst_n)
    if (!rst_n)
      current_state <= 3'h0;
    else
      current_state <= _076_;
  function [31:0] _105_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _105_ = b[31:0];
      3'b?1?:
        _105_ = b[63:32];
      3'b1??:
        _105_ = b[95:64];
      default:
        _105_ = a;
    endcase
  endfunction
  assign _022_ = _105_(32'd0, { _083_, 24'h000000, div3_quotient, 23'h000000, div7_quotient }, { _025_, _024_, _023_ });
  assign _023_ = base_reg == 32'd7;
  assign _024_ = base_reg == 32'd3;
  assign _025_ = base_reg == 32'd2;
  assign _026_ = _027_ ? _022_ : quotient_reg;
  assign _027_ = current_state == 3'h2;
  function [31:0] _111_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _111_ = b[31:0];
      3'b?1?:
        _111_ = b[63:32];
      3'b1??:
        _111_ = b[95:64];
      default:
        _111_ = a;
    endcase
  endfunction
  assign _028_ = _111_(32'd0, { 31'h00000000, k_reg[0], 30'h00000000, div3_remainder, 29'h00000000, div7_remainder }, { _031_, _030_, _029_ });
  assign _029_ = base_reg == 32'd7;
  assign _030_ = base_reg == 32'd3;
  assign _031_ = base_reg == 32'd2;
  assign _032_ = _033_ ? _028_ : remainder_reg;
  assign _033_ = current_state == 3'h2;
  function [31:0] _117_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _117_ = b[31:0];
      2'b1?:
        _117_ = b[63:32];
      default:
        _117_ = a;
    endcase
  endfunction
  assign _034_ = _117_(32'd2, 64'h0000000300000007, { _036_, _035_ });
  assign _035_ = base_sel == 2'h2;
  assign _036_ = base_sel == 2'h1;
  assign _037_ = _038_ ? _034_ : base_reg;
  assign _038_ = current_state == 3'h1;
  function [31:0] _122_;
    input [31:0] a;
    input [95:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _122_ = b[31:0];
      3'b?1?:
        _122_ = b[63:32];
      3'b1??:
        _122_ = b[95:64];
      default:
        _122_ = a;
    endcase
  endfunction
  assign _039_ = _122_(power_reg, { _084_, _085_, _086_ }, { _042_, _041_, _040_ });
  assign _040_ = base_reg == 32'd7;
  assign _041_ = base_reg == 32'd3;
  assign _042_ = base_reg == 32'd2;
  function [31:0] _126_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _126_ = b[31:0];
      2'b1?:
        _126_ = b[63:32];
      default:
        _126_ = a;
    endcase
  endfunction
  assign _043_ = _126_(power_reg, { _045_, _039_ }, { _048_, _044_ });
  assign _044_ = current_state == 3'h4;
  function [31:0] _128_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _128_ = b[31:0];
      2'b1?:
        _128_ = b[63:32];
      default:
        _128_ = a;
    endcase
  endfunction
  assign _045_ = _128_(32'd32768, 64'h0000555500002492, { _047_, _046_ });
  assign _046_ = base_sel == 2'h2;
  assign _047_ = base_sel == 2'h1;
  assign _048_ = current_state == 3'h1;
  assign _049_ = _050_ ? _014_ : acc_reg;
  function [31:0] _133_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _133_ = b[31:0];
      2'b1?:
        _133_ = b[63:32];
      default:
        _133_ = a;
    endcase
  endfunction
  assign _051_ = _133_(acc_reg, { 32'h00000000, _049_ }, { _053_, _052_ });
  assign _052_ = current_state == 3'h3;
  assign _053_ = current_state == 3'h1;
  assign _054_ = _055_ ? acc_reg : result;
  assign _055_ = current_state == 3'h6;
  function [31:0] _138_;
    input [31:0] a;
    input [63:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _138_ = b[31:0];
      2'b1?:
        _138_ = b[63:32];
      default:
        _138_ = a;
    endcase
  endfunction
  assign _056_ = _138_(k_reg, { _058_, quotient_reg }, { _060_, _057_ });
  assign _057_ = current_state == 3'h4;
  assign _058_ = _059_ ? k_in : k_reg;
  assign _060_ = current_state == 3'h0;
  assign _061_ = _062_ ? 1'h0 : 1'h1;
  assign _063_ = _064_ ? _061_ : ready;
  assign _064_ = current_state == 3'h0;
  function [0:0] _145_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _145_ = b[0:0];
      2'b1?:
        _145_ = b[1:1];
      default:
        _145_ = a;
    endcase
  endfunction
  assign _065_ = _145_(done, 2'h1, { _067_, _066_ });
  assign _066_ = current_state == 3'h6;
  assign _067_ = current_state == 3'h0;
  assign _068_ = _069_ ? 3'h6 : 3'h2;
  assign _070_ = _071_ ? _068_ : 3'hx;
  assign _071_ = current_state == 3'h5;
  assign _072_ = _073_ ? 3'h1 : current_state;
  assign _074_ = _075_ ? _072_ : 3'hx;
  assign _075_ = current_state == 3'h0;
  function [2:0] _154_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _154_ = b[2:0];
      6'b????1?:
        _154_ = b[5:3];
      6'b???1??:
        _154_ = b[8:6];
      6'b??1???:
        _154_ = b[11:9];
      6'b?1????:
        _154_ = b[14:12];
      6'b1?????:
        _154_ = b[17:15];
      default:
        _154_ = a;
    endcase
  endfunction
  assign _076_ = _154_(3'h0, { _012_, 12'h4e5, _013_ }, { _082_, _081_, _080_, _079_, _078_, _077_ });
  assign _077_ = current_state == 3'h5;
  assign _078_ = current_state == 3'h4;
  assign _079_ = current_state == 3'h3;
  assign _080_ = current_state == 3'h2;
  assign _081_ = current_state == 3'h1;
  assign _082_ = current_state == 3'h0;
  assign _083_ = k_reg >> $signed(32'd1);
  assign _084_ = power_reg >> $signed(32'd1);
  assign _085_ = _019_ >> $signed(32'd16);
  assign _086_ = _020_ >> $signed(32'd16);
  div_mod_3 div3_inst (
    .n(k_reg[7:0]),
    .quotient(div3_quotient),
    .remainder(div3_remainder)
  );
  div_mod_7 div7_inst (
    .n(k_reg[8:0]),
    .quotient(div7_quotient),
    .remainder(div7_remainder)
  );
  assign _007_ = _026_;
  assign _009_ = _032_;
  assign _001_ = _037_;
  assign _006_ = _043_;
  assign _050_ = _021_;
  assign _000_ = _051_;
  assign _010_ = _054_;
  assign _059_ = start;
  assign _004_ = _056_;
  assign _062_ = start;
  assign _008_ = _063_;
  assign _003_ = _065_;
  assign _069_ = _015_;
  assign _013_ = _070_;
  assign _073_ = start;
  assign _012_ = _074_;
  assign _011_ = _076_;
  assign _005_ = _011_;
  assign _002_ = next_state;
  assign next_state = _076_;
endmodule
