"""
ilds.py

This code implements two low-discrepancy sequence generators: the van der Corput sequence
and the Halton sequence (specific for integer output). These sequences are used to generate
evenly distributed points in a space, which can be useful for various applications like
sampling, optimization, or numerical integration.

The code defines three main components: a function called vdc_i, and two classes named
VdCorput and Halton.

The vdc_i function is the core of the van der Corput sequence generation. It takes an integer count,
a base (default 2), and a scale (default 10) as inputs. It converts the number count from the given
base to a decimal number, using the specified scale for integer output. This function is used to
generate individual elements of the van der Corput sequence.

The VdCorput class is a wrapper around the vdc_i function. It keeps track of the current count
and allows you to generate successive elements of the van der Corput sequence by calling its pop
method. You can also reset the sequence to a specific starting point using the reseed method.

The Halton class generates points in a 2-dimensional space using two van der Corput sequences
with different bases. It creates two VdCorput objects internally and uses them to generate pairs
of numbers. The pop method of the Halton class returns a list of two integers, representing a
point in 2D space.

The main logic flow in this code is the generation of these low-discrepancy sequences. For the
van der Corput sequence, it works by repeatedly dividing the input number by the base and using
the remainders to construct the output number. This process creates a sequence of numbers that
are well-distributed between 0 and N (when properly scaled).

The Halton sequence extends this idea to multiple dimensions by using different bases for each
dimension. In this implementation, it generates 2D points by combining two van der Corput sequences.

The code doesn't take any direct input from the user. Instead, it provides classes and functions that
can be used in other programs to generate these sequences. The output of these generators are
individual numbers (for van der Corput) or pairs of numbers (for Halton) that form the respective sequences.

This code is particularly useful for applications that need well-distributed random-like numbers,
but with more uniformity than typical pseudo-random number generators provide. It's a building
block that can be used in more complex algorithms and simulations.
"""

import threading
from typing import List, Sequence

from lds_gen.lds import GeneratorBase


def vdc_i(count: int, base: int = 2, scale: int = 10) -> int:
    r"""Integer van der Corput sequence in base :math:`b`.

    Reverses the base-:math:`b` expansion of :math:`n` and scales it by
    :math:`b^{\text{scale}}` to produce an integer output:

    .. math::

       \phi_b^{\mathbb{Z}}(n) = \sum_{k=0}^{m} d_k \cdot \frac{b^{\text{scale}}}{b^{k+1}}

    where :math:`d_k` are the base-:math:`b` digits of :math:`n`.

    :param count: The integer :math:`n` to convert
    :param base: The base :math:`b` (default 2)
    :param scale: The number of digits (default 10)
    :return: The integer radical inverse :math:`\phi_b^{\mathbb{Z}}(n)`

    Examples:
        >>> vdc_i(1, 2, 10)
        512
        >>> vdc_i(2, 2, 10)
        256
    """
    factor = base**scale
    reslt = 0
    while count != 0:
        remainder = count % base
        factor //= base
        count //= base
        reslt += remainder * factor
    return reslt


# The `VdCorput` class initializes an object with a base and scale value, and sets the count to 0.
class VdCorput(GeneratorBase[int]):
    def __init__(self, base: int = 2, scale: int = 10) -> None:
        self._base: int = base
        self._scale: int = scale
        self._count: int = 0
        self._count_lock = threading.Lock()

    def value_at(self, n: int) -> int:
        r"""Evaluate the integer sequence value at index :math:`n` (pure).

        :param n: The sequence index.
        :return: The integer van der Corput value for index ``n``.

        Examples:
            >>> vdc = VdCorput(2, 10)
            >>> vdc.value_at(1)
            512
        """
        return vdc_i(n, self._base, self._scale)


class Halton(GeneratorBase[List[int]]):
    """Halton sequence generator

    The `Halton` class is a sequence generator that generates points in a
    2-dimensional space using the Halton sequence. The Halton sequence is a
    low-discrepancy sequence that is often used in quasi-Monte Carlo methods.
    It is generated by iterating over two different bases and calculating the
    fractional parts of the numbers in those bases. The `Halton` class keeps
    track of the current count and bases, and provides a `pop()` method that
    returns the next point in the sequence as a `List[int]`.

    Examples:
        >>> hgen = Halton([2, 3], [11, 7])
        >>> hgen.reseed(0)
        >>> for _ in range(10):
        ...     print(hgen.pop())
        ...
        [1024, 729]
        [512, 1458]
        [1536, 243]
        [256, 972]
        [1280, 1701]
        [768, 486]
        [1792, 1215]
        [128, 1944]
        [1152, 81]
        [640, 810]
    """

    def __init__(self, base: Sequence[int], scale: Sequence[int]) -> None:
        self._count: int = 0
        self._count_lock = threading.Lock()
        self._vdc0 = VdCorput(base[0], scale[0])
        self._vdc1 = VdCorput(base[1], scale[1])

    def value_at(self, n: int) -> List[int]:
        r"""Evaluate the integer 2D Halton point at index :math:`n` (pure).

        .. math::

           H(n) = \bigl(\phi_{b_0}^{\mathbb{Z}}(n),\; \phi_{b_1}^{\mathbb{Z}}(n)\bigr)

        :param n: The sequence index.
        :return: The integer 2D Halton point for index ``n``.
        """
        return [self._vdc0.value_at(n), self._vdc1.value_at(n)]


if __name__ == "__main__":
    import doctest

    doctest.testmod()
